-- pcornet_pedsnet_valueset_map
-- csv needs to be added to a staging environment to load
-- data in 1_setup/data/pcornet_pedsnet_valueset_map.csv
create or replace schema database.pcornet_maps;

CREATE TABLE database.pcornet_maps.pcornet_pedsnet_valueset_map (
	source_concept_class character varying(200),
	target_concept character varying(200),
	pcornet_name character varying(200),
	source_concept_id character varying(200),
	concept_description character varying(200),
	value_as_concept_id character varying(200)
)
;

COPY into database.pcornet_maps.pcornet_pedsnet_valueset_map
from @"<stagename>"/pcornet_pedsnet_valueset_map.csv
FILE_FORMAT = 
    (
        type = csv 
        record_delimiter = '\n' 
        field_delimiter = ',' 
        FIELD_OPTIONALLY_ENCLOSED_BY = '0x22' 
    )
;

-- P2O_ADMITTING_SOURCE_XWALK
CREATE TABLE if not exists database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK 
(
  CDM_SOURCE character varying(20) 
, CDM_TBL character varying(20) 
, SRC_ADMITTING_SOURCE_TYPE character varying(20) NOT NULL 
, SRC_TYPE_DISCRIPTION character varying(100) 
, TARGET_CONCEPT_ID integer 
, TARGET_CONCEPT_NAME character varying(255) 
, TARGET_DOMAIN_ID character varying(20) 
, TARGET_VOCABULARY_ID character varying(30) 
, TARGET_CONCEPT_CLASS_ID character varying(20) 
, TARGET_STANDARD_CONCEPT character varying(1) 
, TARGET_CONCEPT_CODE character varying(50) 
) 
;

Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','AF','Adult  Foster  Home',8882,'(visit) Adult Living Care Facility (concept_id = 8882)','Visit','CMS Place of Service','Visit','S','35');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','AL','Assisted  Living  Facility',8615,'(visit) Assisted Living Facility (concept_id = 8615)','Visit','CMS Place of Service','Visit','S','13');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','AV','Ambulatory  Visit',581478,'(visit) Ambulance Visit (concept_id = 581478)','Visit','Visit','Visit','S','OMOP4822457');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','ED','Emergency  Department',8870,'(visit) Emergency Room - Hospital (concept_id = 8870)','Visit','CMS Place of Service','Visit','S','23');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','HH','Home  Health',38004519,'(visit) Home Health Agency (concept_id = 38004519)','Visit','Medicare Specialty','Visit','S','A4');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','HO','Home  /  Self  Care',32759,'(visit) Home isolation (concept_id = 32759)','Visit','Visit','Visit','S','OMOP4873970');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','HS','Hospice',8546,'(visit) Hospice (concept_id = 8546)','Visit','CMS Place of Service','Visit','S','34');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','IH','Intra-hospital',0,'IH=Intra-hospital','gap','-','-','-','-');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','IP','Other  Acute  Inpatient  Hospital',0,'IP=Other  Acute  Inpatient  Hospital','gap','-','-','-','-');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','NH','Nursing  Home  (Includes  ICF)',8676,'(visit) Nursing Facility (concept_id = 8676)','Visit','CMS Place of Service','Visit','S','32');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','NI','No  information',0,'Gap','gap','-','-','-','-');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','OT','Other',45878142,'(other_ni_unk) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','RH','Rehabilitation  Facility',38004696,'(visit) Radiation Therapy Center (concept_id = 38004696)','Visit','Medicare Specialty','Visit','S','74');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','RS','Residential  Facility',0,'GAP','gap','-','-','-','-');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','SN','Skilled  Nursing  Facility',8863,'(visit) Skilled Nursing Facility (concept_id = 8863)','Visit','CMS Place of Service','Visit','S','31');
Insert into database.pcornet_maps.P2O_ADMITTING_SOURCE_XWALK (CDM_SOURCE,CDM_TBL,SRC_ADMITTING_SOURCE_TYPE,SRC_TYPE_DISCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','UN','Unknown',45877986,'(other_ni_unk) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','LA4489-6');

-- P2O_DEATH_TERM_XWALK
CREATE TABLE if not exists database.pcornet_maps.P2O_DEATH_TERM_XWALK
   (CDM_SOURCE character varying(20),
	CDM_TBL character varying(20),
	CDM_COLUMN_NAME character varying(50),
	SRC_CODE character varying(20),
	SRC_CD_DESCRIPTION character varying(120),
	TARGET_CONCEPT_ID numeric(32,0),
	TARGET_CONCEPT_NAME character varying(250),
	TARGET_DOMAIN_ID character varying(20),
	TARGET_VOCABULARY_ID character varying(30),
	TARGET_CONCEPT_CLASS_ID character varying(20),
	TARGET_STANDARD_CONCEPT character varying(1),
	TARGET_CONCEPT_CODE character varying(50)
   ) ;

Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_DATE_IMPUTE','B','B=Both  month  and  day  imputed',42530742,'(death_date_imputed_42528380) Both month and day imputed (concept_id = 42530742)','Meas Value','LOINC','Answer','S','LA26905-2');

Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_DATE_IMPUTE','D','Day  imputed',42530783,'(death_date_imputed_42528380) Day imputed (concept_id = 42530783)','Meas Value','LOINC','Answer','S','LA26904-5');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_DATE_IMPUTE','M','Month  imputed',42531065,'(death_date_imputed_42528380) Month imputed (concept_id = 42531065)','Meas Value','LOINC','Answer','S','LA26906-0');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_DATE_IMPUTE','N','Not  imputed',42531037,'(death_date_imputed_42528380) Not imputed (concept_id = 42531037)','Meas Value','LOINC','Answer','S','LA21413-2');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_DATE_IMPUTE','NI','No  information',46237210,'(death_date_imputed_42528380) No information (concept_id = 46237210)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_DATE_IMPUTE','OT','Other',45878142,'(death_date_imputed_42528380) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA4489-6');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_DATE_IMPUTE','UN','Unknown',45877986,'(death_date_imputed_42528380) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','OMOP4822220');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','D','Social  Security',32519,'(death_type) US Social Security Death Master File record (concept_id = 32519)','Type Concept','Death Type','Death Type','S','LA46-8');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','L','Other,  locally  defined',45878142,'(other_ni_unk) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','OMOP4822221');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','N','National  Death  Index',32518,'(death_type) Other government reported or identified death (concept_id = 32518)','Type Concept','Death Type','Death Type','S','GAP');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','DR','Derived',0,'GAP','GAP','GAP','GAP',null,'LA21413-2');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','NI','No  information',46237210,'(other_ni_unk) No information (concept_id = 46237210)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','OT','Other',45878142,'(other_ni_unk) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','OMOP4822221');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','S','State  Death  files',32518,'(death_type) Other government reported or identified death (concept_id = 32518)','Type Concept','Death Type','Death Type','S','GAP');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','T','Tumor  data',0,'GAP','GAP','GAP','GAP',null,'LA4489-6');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH','DEATH_SOURCE','UN','Unknown',45877986,'(other_ni_unk) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','LA9206-9');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_CONFIDENCE','E','Excellent',45881924,'(confidence_in_death_cause_42528382) Excellent (concept_id = 45881924)','Meas Value','LOINC','Answer','S','LA8968-5');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_CONFIDENCE','F','Fair',45876387,'(confidence_in_death_cause_42528382) Fair (concept_id = 45876387)','Meas Value','LOINC','Answer','S','LA21413-2');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_CONFIDENCE','NI','No  information',46237210,'(confidence_in_death_cause_42528382) No information (concept_id = 46237210)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_CONFIDENCE','OT','OT=Other',45878142,'(confidence_in_death_cause_42528382) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA8969-3');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_CONFIDENCE','P','P=Poor',45876751,'(confidence_in_death_cause_42528382) Poor (concept_id = 45876751)','Meas Value','LOINC','Answer','S','LA4489-6');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_CONFIDENCE','UN','UN=Unknown',45877986,'(confidence_in_death_cause_42528382) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','LA26680-1');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_TYPE','C','C=Contributory',36309756,'(obs_cause_of_death_seq_42528938) Contributory (concept_id = 36309756)','Meas Value','LOINC','Answer','S','LA26682-7');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_TYPE','I','I=Immediate/Primary',36310205,'(obs_cause_of_death_seq_42528938) Immediate/Primary (concept_id = 36310205)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_TYPE','O','O=Other',45878142,'(obs_cause_of_death_seq_42528938) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA26681-9');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_TYPE','U','U=Underlying',36310984,'(obs_cause_of_death_seq_42528938) Underlying (concept_id = 36310984)','Meas Value','LOINC','Answer','S','LA21413-2');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_TYPE','NI','NI=No  information',46237210,'(obs_cause_of_death_seq_42528938) No information (concept_id = 46237210)','Meas Value','LOINC','Answer','S','LA4489-6');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_TYPE','UN','UN=Unknown',45877986,'(obs_cause_of_death_seq_42528938) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_DEATH_TERM_XWALK
 (CDM_SOURCE,CDM_TBL,CDM_COLUMN_NAME,SRC_CODE,SRC_CD_DESCRIPTION,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE)
 values ('PCORnet','DEATH_CAUSE','DEATH_CAUSE_TYPE','OT','OT=Other',45878142,'(obs_cause_of_death_seq_42528938) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S',null);

ALTER TABLE database.pcornet_maps.P2O_DEATH_TERM_XWALK alter column SRC_CODE SET NOT NULL;
ALTER TABLE database.pcornet_maps.P2O_DEATH_TERM_XWALK alter column CDM_COLUMN_NAME SET NOT NULL;
ALTER TABLE database.pcornet_maps.P2O_DEATH_TERM_XWALK alter column CDM_TBL SET NOT NULL;
ALTER TABLE database.pcornet_maps.P2O_DEATH_TERM_XWALK alter column CDM_SOURCE SET NOT NULL;

-- P2O_DISCHARGE_STATUS_XWALK
CREATE TABLE if not exists database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK 
(
  CDM_SOURCE character varying(20) 
, CDM_TBL character varying(20) 
, SRC_DISCHARGE_STATUS character varying(20) NOT NULL 
, SRC_DISCHARGE_STATUS_DISCRP character varying(200) 
, TARGET_CONCEPT_ID integer
, TARGET_CONCEPT_NAME character varying(200) 
, TARGET_DOMAIN_ID character varying(20) 
, TARGET_VOCABULARY_ID character varying(30) 
, TARGET_CONCEPT_CLASS_ID character varying(20) 
, TARGET_STANDARD_CONCEPT character varying(1) 
, TARGET_CONCEPT_CODE character varying(50) 
) 
;

Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','AF','Adult  Foster  Home',8882,'(visit) Adult Living Care Facility (concept_id = 8882)','Visit','CMS Place of Service','Visit','S','35');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','AL','Assisted  Living  Facility',8615,'(visit) Assisted Living Facility (concept_id = 8615)','Visit','CMS Place of Service','Visit','S','13');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','AM','Against  Medical  Advice',0,'GAP','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','AW','Absent  without  leave',0,'GAP','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','EX','Expired',0,'GAP','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','HH','Home  Health',38004519,'(visit) Home Health Agency (concept_id = 38004519)','Visit','Medicare Specialty','Visit','S','A4');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','HO','Home  /  Self  Care',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','HS','Hospice',8546,'(visit) Hospice (concept_id = 8546)','Visit','CMS Place of Service','Visit','S','34');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','IP','Other  Acute  Inpatient  Hospital',0,'GAP','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','NH','Nursing  Home  (Includes  ICF)',8676,'(visit) Nursing Facility (concept_id = 8676)','Visit','CMS Place of Service','Visit','S','32');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','NI','No  information',45877986,'(other_ni_unk) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','LA4489-6');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','OT','Other',45878142,'(other_ni_unk) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','RH','Rehabilitation  Facility',38004526,'(visit) Rehabilitation Agency (concept_id = 38004526)','Visit','Medicare Specialty','Visit','S','B4');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','RS','Residential  Facility',8957,'(visit) Residential Substance Abuse Treatment Facility (concept_id = 8957)','Visit','CMS Place of Service','Visit','S','55');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','SH','Still  In  Hospital',38004515,'(visit) Hospital (concept_id = 38004515)','Visit','Medicare Specialty','Visit','S','A0');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','SN','Skilled  Nursing  Facility',8863,'(visit) Skilled Nursing Facility (concept_id = 8863)','Visit','CMS Place of Service','Visit','S','31');
Insert into database.pcornet_maps.P2O_DISCHARGE_STATUS_XWALK (CDM_SOURCE,CDM_TBL,SRC_DISCHARGE_STATUS,SRC_DISCHARGE_STATUS_DISCRP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','UN','Unknown',45877986,'(other_ni_unk) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','LA4489-6');

-- P2O_VITAL_TERM_XWALK

CREATE TABLE if not exists database.pcornet_maps.P2O_VITAL_TERM_XWALK 
(
  SRC_CDM character varying(20) 
, SRC_CDM_TBL character varying(30) 
, SRC_CDM_COLUMN character varying(50) 
, SRC_CODE character varying(20) 
, SRC_CODE_DESCRIP character varying(250) 
, TARGET_CONCEPT_ID integer 
, TARGET_CONCEPT_NAME character varying(200) 
, TARGET_DOMAIN_ID character varying(20) 
, TARGET_VOCABULARY_ID character varying(30) 
, TARGET_CONCEPT_CLASS_ID character varying(20) 
, TARGET_STANDARD_CONCEPT character varying(2) 
, TARGET_CONCEPT_CODE character varying(50) 
) ;


Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','DIASTOLIC_BP_POSITION','01','01=Sitting',3034703,'Diastolic blood pressure--sitting','Measurement','SNOMED','Observable Entity','S','163035008');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','DIASTOLIC_BP_POSITION','02','02=Standing',3019962,'Diastolic blood pressure--standing','Measurement','SNOMED','Observable Entity','S','163034007');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','DIASTOLIC_BP_POSITION','03','03=Supine',36304130,'Diastolic blood pressure-lying L-lateral position','Measurement','SNOMED','Observable Entity','S','163033001');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','DIASTOLIC_BP_POSITION','NI','NI=No  information',4154790,'Diastolic blood pressure','Meas Value','LOINC','Answer','S','LA21413-2');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','DIASTOLIC_BP_POSITION','OT','OT=Other',4154790,'(other_ni_unk) Other','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','DIASTOLIC_BP_POSITION','UN','UN=Unknown',4154790,'(other_ni_unk) Unknown','Meas Value','LOINC','Answer','S','LA4489-6');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SYSTOLIC_BP_POSITION','01','01=Sitting',3018586,'Systolic blood pressure--sitting','Measurement','SNOMED','Observable Entity','S','163035008');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SYSTOLIC_BP_POSITION','02','02=Standing',3035856,'Systolic blood pressure--standing','Measurement','SNOMED','Observable Entity','S','163034007');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SYSTOLIC_BP_POSITION','03','03=Supine',36303812,'Systolic blood pressure-lying L-lateral position','Measurement','SNOMED','Observable Entity','S','163033001');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SYSTOLIC_BP_POSITION','NI','NI=No  information',4152194,'Systolic blood pressure','Meas Value','LOINC','Answer','S','LA21413-2');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SYSTOLIC_BP_POSITION','OT','OT=Other',4152194,'(other_ni_unk) Other','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SYSTOLIC_BP_POSITION','UN','UN=Unknown',4152194,'(other_ni_unk) Unknown','Meas Value','LOINC','Answer','S','LA4489-6');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','01','01=Current  every  day  smoker',45881517,'(obs_smoking_status_43054909) Current every day smoker (concept_id = 45881517)','Meas Value','LOINC','Answer','S','LA18976-3');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','02','02=Current  some  day  smoker',45884037,'(obs_smoking_status_43054909) Current some day smoker (concept_id = 45884037)','Meas Value','LOINC','Answer','S','LA18977-1');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','03','03=Former  smoker',45883458,'(obs_smoking_status_43054909) Former smoker (concept_id = 45883458)','Meas Value','LOINC','Answer','S','LA15920-4');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','04','04=Never  smoker',45879404,'(obs_smoking_status_43054909) Never smoker (concept_id = 45879404)','Meas Value','LOINC','Answer','S','LA18978-9');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','05','05=Smoker,  current  status  unknown',45881518,'(obs_smoking_status_43054909) Smoker, current status unknown (concept_id = 45881518)','Meas Value','LOINC','Answer','S','LA18979-7');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','06','06=Unknown  if  ever  smoked',45885135,'(obs_smoking_status_43054909) Unknown if ever smoked (concept_id = 45885135)','Meas Value','LOINC','Answer','S','LA18980-5');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','07','07=Heavy  tobacco  smoker',45884038,'(obs_smoking_status_43054909) Heavy tobacco smoker (concept_id = 45884038)','Meas Value','LOINC','Answer','S','LA18981-3');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','08','08=Light  tobacco  smoker',45878118,'(obs_smoking_status_43054909) Light tobacco smoker (concept_id = 45878118)','Meas Value','LOINC','Answer','S','LA18982-1');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','NI','NI=No  information',46237210,'(other_ni_unk) No information (concept_id = 46237210)','Meas Value','LOINC','Answer','S','LA21413-2');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','OT','OT=Other',45878142,'(other_ni_unk) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','SMOKING','UN','UN=Unknown',45878142,'(other_ni_unk) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO','01','01=Current  user',36307579,'(obs_tobacco_use_36305168) Current some day user (concept_id = 36307579)','Meas Value','LOINC','Answer','S','LA28392-1');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO','02','02=Never',36308879,'(obs_tobacco_use_36305168) Never used (concept_id = 36308879)','Meas Value','LOINC','Answer','S','LA4519-0');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO','03','03=Quit/former  user',36307819,'(obs_tobacco_use_36305168) Former user (concept_id = 36307819)','Meas Value','LOINC','Answer','S','LA28393-9');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO','04','04=Passive  or  environmental  exposure',37017812,'(obs_tobacco_use_36305168) Environmental tobacco smoke exposure (concept_id = 37017812)','Observation','SNOMED','Observable Entity','S','714151003');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO','06','06=Not  asked',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO','NI','NI=No  information',46237210,'(other_ni_unk) No information (concept_id = 46237210)','Meas Value','LOINC','Answer','S','LA21413-2');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO','OT','OT=Other',45877986,'(other_ni_unk) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','LA4489-6');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO','UN','UN=Unknown',45877986,'(obs_tobacco_use_36305168) Unknown (concept_id = 45877986)','Meas Value','LOINC','Answer','S','LA4489-6');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO_TYPE','01','01=Smoked  tobacco  only',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO_TYPE','02','02=Non-smoked  tobacco  only',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO_TYPE','03','03=Use  of  both  smoked  and  non-smoked  tobacco  products',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO_TYPE','04','04=None',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO_TYPE','05','05=Use  of  smoked  tobacco  but  no  information  about  non-smoked  tobacco  use',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO_TYPE','NI','NI=No  information',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO_TYPE','OT','OT=Other',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','TOBACCO_TYPE','UN','UN=Unknown',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','VITAL_SOURCE','HC','HC=Healthcare  delivery  setting',32489,'(measurement_type) Accelerated lab result (concept_id = 32489)','Type Concept','Meas Type','Meas Type','S','OMOP4822268');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','VITAL_SOURCE','HD','HD=Healthcare  device  direct  feed',32489,'(measurement_type) Accelerated lab result (concept_id = 32489)','Type Concept','Meas Type','Meas Type','S','OMOP4822268');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','VITAL_SOURCE','DR','DR=Derived',45754907,'(measurement_type) Derived value (concept_id = 45754907)','Type Concept','Meas Type','Meas Type','S','OMOP4822276');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','VITAL_SOURCE','NI','NI=No  information',46237210,'(other_ni_unk) No information (concept_id = 46237210)','Type Concept','Meas Type','Meas Type','S','OMOP4822272');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','VITAL_SOURCE','OT','OT=Other',45878142,'(other_ni_unk) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA46-8');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','VITAL_SOURCE','PD','PD=Patient  device  direct  feed',0,'Gap','-','-','-','-','-');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','VITAL_SOURCE','PR','PR=Patient-reported',44818704,'(measurement_type) Patient reported value (concept_id = 44818704)','Type Concept','Meas Type','Meas Type','S','OMOP4822272');
Insert into database.pcornet_maps.P2O_VITAL_TERM_XWALK (SRC_CDM,SRC_CDM_TBL,SRC_CDM_COLUMN,SRC_CODE,SRC_CODE_DESCRIP,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','VITAL','VITAL_SOURCE','UN','UN=Unknown',45878142,'(other_ni_unk) Other (concept_id = 45878142)','Meas Value','LOINC','Answer','S','LA46-8');

-- VISIT_XWALK

CREATE TABLE if not exists database.pcornet_maps.VISIT_XWALK 
(
  CDM_NAME character varying(100) 
, CDM_TBL character varying(100) 
, SRC_VISIT_TYPE character varying(100) 
, FHIR_CD character varying(100) 
, TARGET_CONCEPT_ID integer NOT NULL 
, TARGET_CONCEPT_NAME character varying(255) NOT NULL 
, TARGET_DOMAIN_ID character varying(20) NOT NULL 
, TARGET_VOCABULARY_ID character varying(20) NOT NULL 
, TARGET_CONCEPT_CLASS_ID character varying(20) NOT NULL 
, TARGET_STANDARD_CONCEPT character varying(1) 
, TARGET_CONCEPT_CODE character varying(50) NOT NULL 
) 
;

Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','AV','AMB',9202,'Outpatient Visit','Visit','Visit','Visit Type','S','19700101');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','ED','EMER',9203,'Emergency Room Visit','Visit','Visit','Visit Type','S','19700101');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','EI','ACUTE',262,'Emergency Room Visit','Visit','Visit','Visit Type','S','19700101');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','IC',null,42898160,'Institutional  Professional  Consult','Visit','Visit','Visit Type','S','19700101');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','IP','IMP',9201,'Inpatient Hospital Stay','Visit','Visit','Visit Type','S','19700101');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','NI',null,0,'No information','Visit','Visit','Visit Type','S','25569');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','IS','NONAC',42898160,'Non-Acute Institutional Stay','Visit','Visit','Visit Type','S','19700101');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','OA','AMB',9202,'Outpatient Visit','Visit','Visit','Visit Type','S','19700101');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','OS','X',581385,'Observation Stay','Visit','Visit','Visit Type','S','19700101');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','OT',null,0,'Other','Visit','Visit','Visit Type','S','25569');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('PCORnet','ENCOUNTER','UN',null,0,'Unknown','Visit','Visit','Visit Type','S','25569');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','VISIT_DIMENSION','EI','ACUTE',262,'Emergency Department Visit','Visit','Visit','Visit Type','S','ERIP');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','VISIT_DIMENSION','E','EMER',9203,'Emergency Department Visit','Visit','Visit','Visit Type','S','ER');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','VISIT_DIMENSION','I','ACUTE',9201,'Inpatient Hospital Stay','Visit','CMS Place of Service','Visit Type','S','21');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','VISIT_DIMENSION','N',null,0,'No Information','Visit','CMS Place of Service','Visit Type','S','46237210');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','VISIT_DIMENSION','NA','NONAC',9201,'Non-Acute Hospital Stay','Visit','CMS Place of Service','Visit Type','S','A0');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','VISIT_DIMENSION','X',null,9202,'X Other Ambulatory Visit','Visit','Visit','Visit','S','OP');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','VISIT_DIMENSION','O','AMB',9202,'O Ambulatory Visit','Visit','Visit','Visit','S','OP');
Insert into database.pcornet_maps.VISIT_XWALK (CDM_NAME,CDM_TBL,SRC_VISIT_TYPE,FHIR_CD,TARGET_CONCEPT_ID,TARGET_CONCEPT_NAME,TARGET_DOMAIN_ID,TARGET_VOCABULARY_ID,TARGET_CONCEPT_CLASS_ID,TARGET_STANDARD_CONCEPT,TARGET_CONCEPT_CODE) values ('I2B2ACT','VISIT_DIMENSION','OP','IC',9202,'OP Outpatient  Visit','Visit','Visit','Visit','S','OP');
